### PR TITLE
Removed gcData from GC blob in summary in snpashot tests as GC is disabled

### PR DESCRIPTION
**Pull request by agarwal-navin**
Corresponding PR in FluidFramework repo - https://github.com/microsoft/FluidFramework/pull/6773

Remove gcData from the GC blob in summary In the snapshot tests because GC is disabled.

### CODE REVIEW

**Comment by vladsud** [comment]
I'm a bit confused RE "because GC is disabled".
That change is not supposed to change whether we write data or not, is it?

**Comment by agarwal-navin** [comment]
> I'm a bit confused RE "because GC is disabled".
> That change is not supposed to change whether we write data or not, is it?

When GC is disabled, we will still write GC blob in the summary. However, with this change, we do not use the `gcData` returned by `summarize` to write into the GC blob. Instead, we get the `gcData` from `summarizerNode` which stores the value returned by `getGCData`. Since, GC doesn't run in these tests, the `gcData` in `summarizerNode` is empty.

Note: I am contemplating not even writing the GC blob if GC is disabled. Otherwise, that unnecessarily increases the snapshot size.

**Comment by vladsud** [comment]
But shouldn't we enable GC in these tests?
While change is correct, it's a loss of coverage, I'd rather seek a way for these tests to better represent what we ship.

**Comment by agarwal-navin** [comment]
Since these snapshots are old, they do not meet the watermark, i.e., they do not have the ".metadata" blob that enables GC. The only other way to enable GC is via localStorage which we cannot do in node.
We can either manually update these snapshots to contain a ".metadata" blob or we can add more referenence snapshots that have this blob.

**Comment by vladsud** [comment]
Got it! I assume we do not have more "modern" file in library and need to add it to make sure we do have some coverage going forward, right? If so, can it be done before removal happens, such that we have continuity in coverage?

**Review by vladsud — APPROVED** [review]

**Comment by agarwal-navin** [comment]
Adding "modern" file to the snapshot tests is complicated because of detached container. We will have to add the initial snapshot that is generated when the container attaches. Also, the `snapshot` API doesn't support running GC and I will have to add that.
I created an issue to track this - https://github.com/microsoft/FluidFramework/issues/6812. I will work on it next.

**Pull request merged**
